apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/hostUsers
        value: false


resources:
- openweb-ui.yml
- namespace.yml
- n8n.yml
- alfred.yml


replicas:
  - name: alfred
    count: 0
  - name: n8n
    count: 1
  - name: open-web-ui # Don't use it enough and consumes a lot of memory
    count: 0
