apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/hostUsers
        value: false


resources:
- openweb-ui.yml
- namespace.yml
- n8n.yml
- alfred.yml
