---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karakeep-secrets
  namespace: bots
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgALm1V/ekxeK15IU7HWwB9SBrJEXmR2yrd8Ydh5CoN81k/UFhxSw0dNG6NCQO26xOJqOJjQR/gKNSVc1xrmqCieMvMnnZe3Q6uIH8D5wxWQ921t8xRPcAkDmBf9SM7YPEv5BPJUksht1Q7VgYRwt2mW2+ztt+vX4AkC3CA+VYO8BD4c6ivoaj0zSoEa5GyrHLve8M8Hg2Jp5i7K/Bfby8p2ewB5lf5LHEWiaGUounsLavikQKqmLz6EArriifP+OplVo6y9URJ6+qvutRoVOdvQSIdFfyZrD7ztZ6u9luGm8wSIkw9hPhaNUiepaz+dlBMwR0eS5jBrV8oIMfc/8a6mjzVNz8Pz5R4IC6++EiDS53WnuvhtZZX4N+vQ9lUJ6DdtM0ZM0lF0LxuRx9toHVhxgH35J+8YZfxPsMtW+gaokweknv/fi+yETD89k9Vmy6CAbx3di8CflSz38NcWuL2/zqk/LccZfkfPgCChR0EznfG9Y3QRBYM/Djo0mPqMj4tzGemJNzbtcTe9QShfznnKaLmHuAQScmwXeemo+wtlc8MuNVx5AUyvv5rXD9sppVH25VMtChOjBrW7OhVk8zkzyxBtg6V3a/8PAMN/2/7geceF5QJpe23jg6De9jDdSluRzN2i7KgFn6PAhGV9Hgyx0rqMC/Kus8wPrm9boKOULFyITnUs9XGJGZCl8cA4ii7Hs3jv9fmBwrqV++Te5jvm/DPWoN6zTByO3g9O+sfYOU83uu2UOEK2bKXIAkqXc+Z5Q5wzcUTyqxP1hDl+O4oh
  template:
    metadata:
      creationTimestamp: null
      name: karakeep-secrets
      namespace: bots
