---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-htp-file
  namespace: monitoring
spec:
  encryptedData:
    .htpasswd: AgBG0q55gZpX3PA8UxUM9d9/0ApE5oGP5ARYAQbu4hf8oBtT+WTkWWWiMBjgIMCPQ/H/6OtOGrtJFsGWKN/hJP1N7tb6fVQrZmRS+ntwEVHjrCzdgQrMAxqay2Yyiz+Y+Ze7EFLg68KoZN3U0lzz0bwIwlYLI22tbesPPBWWpbH+8m76/pneWmjDN/9Q1LejBXTmq0xDUcBcQQlkr0hQCDC9ynFqRKhJpzkXTyo60d4aNliH9StrPMp12c7Gjk5WUL6Cern7Mw1VWMe0XRLe7XKULVVfcP1UEoIWCIeliksOpF7kw7liQ80iwJzZiI9e+IeFk0ZIcM9ad4MLOHNtKR82Mlt0A6aPxNJogPq0Dm/IthZ9Tm1sdDELYwB7XXoTVBm8ZX/r8T8tkU0wul8a+obTAf8PZP6lyI4SyHHx1799i0f8LsgPSJYVXbXZI/JcuP2WtjJiXyuGYx7fZR467Bhx5VBNUfrfPRDWJDYm/cyFg2k3RNbN2HbYG3WbnM/DiA1xjeBtm5zCmb1adzLAFOnTtQiwBn5HPYv8NmHOEcnmTQMY0w8U8xKPtAknuup5rODKQuDY+K0+JVEaiJ20EMRFgNIT9L5PZlmSQIbPl17DxQO0peSQjE0EBZIsPIYzqAedrXwNcdUJCkiXynd+4zE9Wzjt136hcFECuLqyZTd53/cDKn9q6RiWr70w0onAzY/XXCJexbC8Rvwt6Fo8ntqumPeZJjRttVHUneN77wZwcV9QS709stk+RfkO3rAu
  template:
    metadata:
      creationTimestamp: null
      name: loki-htp-file
      namespace: monitoring
