---

where_to_mount_storage_device: /mnt/overlay2
mounted_path: "{{ where_to_mount_storage_device }}{{ defualt_relative_docker_data_path }}"


parition_number: 1
new_partition: /dev/sdb{{ parition_number }} # !!! DANGEROUS CONSTANT !!! # dont want name conflictions
file_system_type: ext4

media_path_tv: "{{ mounted_path }}/media/tv"
media_path_movies: "{{ mounted_path }}/media/movies"
media_path_books: "{{ mounted_path }}/media/books"
media_path_music: "{{ mounted_path }}/media/music"
media_path_downloads: "{{ mounted_path }}/media/downloads"

users:
  - name: servarr
    PUID: 1015

  - name: tors
    PUID: 1006
  
  - name: jellyfin
    PUID: 1016

