---

- name: Make Docker Volume Directory
  become: true
  ansible.builtin.file:
    mode: u=rwx,g=rwx,o=
    path: "{{ defualt_relative_docker_data_path }}"
    state: directory

- name: Make Traefik user
  become: true
  ansible.builtin.user:
    name: '{{ traefik_local_user }}'

- name: Make Traefik directory
  become: true
  ansible.builtin.file:
    mode: u=rwx,g=rwx,o=
    path: "{{ defualt_relative_docker_data_path }}/traefik"
    state: directory
    owner: "{{ traefik_local_user }}"

- name: Copy traefik config files
  become: true
  ansible.builtin.copy:
    mode: u=rw,g=r,o=
    src: "{{ item }}"
    dest: "{{ defualt_relative_docker_data_path }}/traefik/{{ item }}"
    owner: "{{ traefik_local_user }}"
  loop: '{{ traefik_files }}'

- name: Make ACME json file
  become: true
  ansible.builtin.file:
    mode: u=rw,g=,o=
    path: "{{ defualt_relative_docker_data_path }}/traefik/acme.json"
    state: file
    owner: "{{ traefik_local_user }}"

- name: Create Traefik Resource
  vars:
    docker_template_files:
      - src: traefik-compose.yml.j2
        dest_name: traefik.compose
    compose_file: traefik.compose
    compose_project_name: traefik
  ansible.builtin.include_tasks: ../tasks/docker-compose-up.yml
