apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bots

resources:
- eventscraper.yml
- namespace.yml
- it-tools.yml
- karakeep.yml
- gitea.yml
- open-project.yml



replicas:
  - name: eventscraper
    count: 1
  - name: gitea
    count: 1
  - name: ittool
    count: 1
  - name: karakeep
    count: 1
  - name: openproject
    count: 0
