---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-login
  namespace: monitoring
spec:
  encryptedData:
    LOKI_PASSWD: AgBIuNssbk+6GoSIcQMkhNJOQxkooLmEwFc4jXAJFD4tY1vu1NgUVZcYrQb7/+VoXdfBTKq79OlPhE6AU+nexOTwtY9WE/PhBQZgq8yvDNMAAQTx300EOStD83THjVs+xF8SFAnVrHsr/26Fd/1kknZFmKq/dleEKM0cvW1DbZ9PZ+SOb6UrUNnghKhDsvScSW9imOhPz529S486CVA08WHjTPlUkVAR8+CcwRF8E7xR+VgQAiXvSqiOTZzst57fOXxmvE4rBFMP87Ug+oNPXGhk2lI1cCvoxOt4Zmwz4LSmAO7iA3fowRtQsIrDXGQ5snCf6WfBcjHiOoxcfS5Uh9ueGqW9zgrNGiiU5nXL8klLktiHWecVZMP0wJ+ohS2APTuvHi0I6FdTMDVfqBwUofaDxubZpzMBV4VTulN+Oadi1MjlxZf425BA/Zamz7XKSbSqvxVoT96lkcD/lXa8HUWnsvG5vX5J23cwEpDSLEAIPEGfVhEZA3B5GHyuCCGRmxfLCp+ttahdRVl3HRQl864kdCactqmFvDtH4xk5/7Ycid74aJwmShoKXW3ESd4UJ3FnuaPJUEZSR3kS6OGi7xWKXBWTSpnQhCiZg4AazdzEsijGx2US3rG5xjy6zSh0zkcsBX5VRfQMCEdHJigf+QAfj5Hod+v6/dVjjfNFwNwQJDnnRaf6yJDMGP1MMrzTNhvsxKKXAQMCKBYM5kfoUw==
    LOKI_USERNAME: AgBUM5zN9OZSKh41EtdvPw0Xqh8+B8xB4D3Kpakq1jUY2jN2hVcj+o+wROVvtOVcYgiCaQairwRliApYKesoOkNa+uYxS9sBWY+/u+qUihWBh1QIORtbaUr5ukvHvjKQO8ZbXSgeptof7DKc3Ekx2cDFnLKTxxC0IZeBpfbs29mBLIR/Zxb8p3w6zcMcwd9oMGP4gYZdiPBdWgIJdwHD/US7QYHQfPouxP9WqyhJXiSK7lXEYSw33BZ91levdTHYM/I66lzoxX4mVcLSscXUrIt9cTcLKVLHIqQPUt+fSTlNI5Qm2/+RXaoIg8yKh5OwhwCj4haTZtxQIzc0fMPfeqCMf5dC1TXHZ2MhxI3eWAwovei2NYvC82VD5gpXHd6rttdwxoVBjSwzQErcXw7fqwloc/zatfHUkAFTzb6qh56lBi8xYNTv1s7z3F58lOcHylg6Rmrx+gSemKA3TH5SOpnXqC8rqiG+Geczmt2c7nDBfbfbmGfakvhVcRc2gWtZMr4yQqDaW7GgLMW4wuhbVvwej+tvkWZw7onOaXYNTeoRx0QrE5eMf8cGJG1tO8QuH0UXRwZ+qveGlBmRjP0W/ZRoVhX2+p9xKEfoTIgcskzwaPzflUPMH29Jph7l/2ldk3wlnUzH7biXJfebRlZSOdwRPHzyCfwCCQYJqfxpQ38havyPX1RS9MdqY4j/sLpV2NWvZHA7/ml9
  template:
    metadata:
      creationTimestamp: null
      name: loki-login
      namespace: monitoring
