http:
 #region routers 
  routers:

    # Admin
    ### Proxmox
    alienwareprox:
      entryPoints:
        - "https"
      rule: "Host(`alienwareprox.homelab.ezequielvalencia.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: alienwareprox
    pcprox:
      entryPoints:
        - "https"
      rule: "Host(`pcprox.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pcprox
    zpcprox:
      entryPoints:
        - "https"
      rule: "Host(`zpcprox.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: zpcprox
    
    ### Other
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - redirectregex-pihole
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`truenas.homelab.ezequielvalencia.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: truenas
    

    # Tools
    
    dashy:
      entryPoints:
        - "https"
      rule: "Host(`dashy.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: dashy

#endregion
#region services
  services:

    # Admin
    alienwareprox:
      loadBalancer:
        servers:
          - url: "https://10.0.0.4:8006"
        passHostHeader: true
    pcprox:
      loadBalancer:
        servers:
          - url: "https://10.0.0.5:8006"
        passHostHeader: true
    zpcprox:
      loadBalancer:
        servers:
          - url: "https://10.0.0.14:8006"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.0.6:5790"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "https://10.0.0.13"
        passHostHeader: true
    
    # Tools
    dashy:
      loadBalancer:
        servers:
          - url: "http://10.0.0.8:8080"
        passHostHeader: true

#endregion
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    redirectregex-pihole:
      redirectRegex:
        regex: /admin/$
        replacement: /
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.homelab.ezequielvalencia.com"

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/24"
        # - "192.168.0.0/16"
        # - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers