# create kustimization.yaml file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Merge Patch https://stackoverflow.com/questions/76004172/how-to-add-init-container-with-kustomize


resources:
- ./ai/
- ./bots/
- ./media/
- ./monitor/
- ./public-apps/

- ../../../SealedSecrets/production/network
- ../../base/servicemesh

- certs.yml
- ./registry/registry.yml
