apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-apps

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/hostUsers
        value: false

resources:
- three-mix.yml
- ezequiel-backend.yml
- namespace.yml
- ctgrassroots.yml